# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xrOPn_pl3CL87EI5TIAVSn2pzZzTriGi
"""

!pip install streamlit
!pip install pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# PAGE_CONFIG = {"page_title":"NLP_Mail.io","page_icon":":smiley:","layout":"centered"}
# st.beta_set_page_config(**PAGE_CONFIG)
# def main():
# 	st.title("NLP Online formail")
# 	st.subheader("DifferentNLP for Datascientest")
# 	menu = ["Home","IA1","IA2","IA3"]
# 	choice = st.sidebar.selectbox('Menu',menu)
# 	if choice == 'Home':
# 		st.subheader("NLP for Datascientest")	
# if __name__ == '__main__':
# 	main()

!ls

!streamlit run app.py &>/dev/null&

from pyngrok import ngrok
# Setup a tunnel to the streamlit port 8501
public_url = ngrok.connect(port='8502')
public_url

!ps -eaf | grep streamlit

ngrok.kill()

